spring.application.name=gestion_stock

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/stock_db
spring.datasource.username=brayan
spring.datasource.password=superpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true